#ifndef LIBKUNWIND_GLOBAL_H
#define LIBKUNWIND_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBKUNWIND_LIBRARY)
#  define LIBKUNWINDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBKUNWINDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBKUNWIND_GLOBAL_H
